name: run-nua-e2e
run-name: Running e2e NUA tests
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    branches:
      - main
  schedule:
    # run every at every saturdat at 12
    - cron: '25 0 * * 6'
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Launch NucliaDB in docker

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r nua/requirements.txt

      - name: Install dependencies
        run: |
          pytest nua/e2e --benchmark-autosave

      - name: Cypress reports
        uses: actions/upload-artifact@v3
        with:
          name: benchmarks-reports
          path: .benchmarks
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`

      - name: Discord notification
        uses: cl8dep/action-discord@0.1
        if: ${{ failure() && github.ref_name == 'main' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_NUA }}
          message: |
            ⚠️ tests failed @NUA
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>
          username: 'NUA E2E'