name: run-e2e-stage
run-name: Running Cypress e2e tests on Stage
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    branches:
      - main
  schedule:
    # Run at 00:25 and 12:25 on saturday and sunday
    - cron: '25 0,12 * * 0,6'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Launch NucliaDB in docker
      - run: |
          docker network create nucliadb-network
          docker run -it -d --name pg --network nucliadb-network \
            -p 5432:5432 \
            -e POSTGRES_USER=nucliadb \
            -e POSTGRES_PASSWORD=nucliadb \
            -e POSTGRES_DB=nucliadb \
            postgres:latest
          docker pull nuclia/nucliadb:latest
          docker build -t nucliadb-server .
          docker run --network nucliadb-network \
              --name nucliadb-server \
              -p 8080:8080 \
              -v nucliadb-standalone:/data \
              -e NUCLIA_PUBLIC_URL="https://{zone}.stashify.cloud" \
              -e NUA_API_KEY=${{ secrets.NUA_KEY }} \
              -e DRIVER=PG \
              -e DRIVER_PG_URL="postgresql://nucliadb:nucliadb@pg:5432/nucliadb" \
              nucliadb-server &
      # Install npm dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn install
        env:
          CYPRESS_BASE_URL: https://stashify.cloud
          CYPRESS_BEARER_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          CYPRESS_NUA_KEY: ${{ secrets.NUA_KEY }}
          CYPRESS_USER_NAME: ${{ secrets.USER_NAME }}
          CYPRESS_USER_PWD: ${{ secrets.USER_PWD }}
          CYPRESS_RUNNING_ENV: stage
        # after the test run completes store reports and any screenshots
      - name: Cypress reports
        id: report
        uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.cypress.conclusion == 'failure' }}
        with:
          name: cypress-reports
          path: cypress/reports
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      # After Cypress tests, get logs and upload them
      - name: Capture NucliaDB Logs
        if: always() # Run even if Cypress fails
        run: |
          docker logs nucliadb-server > nucliadb-server.log 2>&1
          docker logs pg > postgres.log
    
      - name: Upload Docker Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: |
            nucliadb-server.log
            postgres.log
          if-no-files-found: ignore          
      - name: Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        if: ${{ failure() && steps.cypress.conclusion == 'failure' && github.ref_name == 'main' }}
        with:
          payload: |
            {
              "text": "⚠️ Cypress E2E failed on Stage\nTriggered by ${{ github.triggering_actor }} \nRun #${{ github.run_number }}: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\nCypress report: ${{ steps.report.outputs.artifact-url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
