name: run-nuclia-e2e-stage
run-name: Running e2e STAGE NUCLIA tests

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/run-e2e-nuclia-stage.yml'
      - 'nuclia_e2e/**'
  workflow_dispatch:  # Allow manual run from any branch
  schedule:
    # Run every day at 04:25
    - cron: '25 4 * * *'
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        shard_index: [0, 1, 2]  # Running tests in 3 parallel shards

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install venv
        run: uv sync --project nuclia_e2e

      - name: Run pre-checks
        run: |
          source nuclia_e2e/.venv/bin/activate
          make -C nuclia_e2e/ lint format-check

      - name: Run tests (Shard ${{ matrix.shard_index }})
        env:
          TEST_EUROPE1_STASHIFY_NUA: ${{ secrets.TEST_EUROPE1_STASHIFY_NUA }}
          STAGE_PERMAMENT_ACCOUNT_OWNER_PAT_TOKEN: ${{ secrets.STAGE_PERMAMENT_ACCOUNT_OWNER_PAT_TOKEN }}
          STAGE_ROOT_PAT_TOKEN: ${{ secrets.STAGE_ROOT_PAT_TOKEN }}
          STAGE_GLOBAL_RECAPTCHA: ${{ secrets.STAGE_GLOBAL_RECAPTCHA }}
          TEST_GMAIL_APP_PASSWORD: ${{ secrets.TEST_GMAIL_APP_PASSWORD }}
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
        run: |
          source nuclia_e2e/.venv/bin/activate && TEST_ENV=stage pytest -sxv -r fEs nuclia_e2e/nuclia_e2e/tests \
            --durations=0 --junitxml=nuclia-${{ matrix.shard_index }}.xml \
            --shard-id=${{ matrix.shard_index }} --num-shards=3

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'nuclia-*.xml' # Collect all test reports from parallel runs

  notify:
    if: ${{ failure() && github.ref_name == 'main' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "⚠️ Tests failed on STAGE\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.NUA_E2E_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
