name: run-e2e-prod
run-name: Running Cypress e2e tests on prod
on:
  push:
    branches:
      - e2e-on-prod
    paths:
      - '.github/workflows/run-e2e-prod.yml'
  workflow_dispatch:
  schedule:
    # Run at minute 45 past every 3rd hour on every day-of-week from Sunday through Saturday.
    - cron: '45 */3 * * 0-6'
  repository_dispatch:
    types: [trigger_e2e]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    permissions:
      contents: read    # actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: e2e-on-prod
          persist-credentials: false
      # Launch NucliaDB in docker
      - run: |
          docker network create nucliadb-network
          docker run -it -d --name pg --network nucliadb-network \
            -p 5432:5432 \
            -e POSTGRES_USER=nucliadb \
            -e POSTGRES_PASSWORD=nucliadb \
            -e POSTGRES_DB=nucliadb \
            postgres:latest
          docker pull nuclia/nucliadb:latest
          docker build -t nucliadb-server .
          docker run --network nucliadb-network \
              -p 8080:8080 \
              --name nucliadb-server \
              -v nucliadb-standalone:/data \
              -e NUA_API_KEY=${{ secrets.NUA_KEY_PROD_EUROPE }} \
              -e DRIVER=PG \
              -e LOG_LEVEL=DEBUG \
              -e DRIVER_PG_URL="postgresql://nucliadb:nucliadb@pg:5432/nucliadb" \
              nucliadb-server &
      # Install npm dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@f790eee7a50d9505912f50c2095510be7de06aa7 # v6.10.9
        with:
          install-command: yarn install
        env:
          CYPRESS_BASE_URL: https://progress.cloud
          CYPRESS_BEARER_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_PROD }}
          CYPRESS_COWORK_BEARER_TOKEN: ${{ secrets.COWORK_PERSONAL_ACCESS_TOKEN_PROD }}
          CYPRESS_NUA_KEY_EUROPE: ${{ secrets.NUA_KEY_PROD_EUROPE }}
          CYPRESS_NUA_KEY_USA: ${{ secrets.NUA_KEY_PROD_USA }}
          CYPRESS_USER_NAME: ${{ secrets.USER_NAME_PROD }}
          CYPRESS_USER_PWD: ${{ secrets.USER_PWD_PROD }}
          CYPRESS_GMAIL_APP_PASSWORD: ${{ secrets.TEST_GMAIL_APP_PASSWORD }}
          CYPRESS_GLOBAL_RECAPTCHA: ${{ secrets.PROD_GLOBAL_RECAPTCHA }}
          CYPRESS_OAUTH_CLIENT_ID: ${{ secrets.PROD_OAUTH_CLIENT_ID }}
          CYPRESS_ROOT_PAT_TOKEN: ${{ secrets.PROD_ROOT_PAT_TOKEN }}
          CYPRESS_RUNNING_ENV: prod
        # after the test run completes store reports and any screenshots
      - name: Cypress reports
        id: report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ failure() && steps.cypress.conclusion == 'failure' }}
        with:
          name: cypress-reports
          path: cypress/reports
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      # After Cypress tests, get logs and upload them
      - name: Capture NucliaDB Logs
        if: always() # Run even if Cypress fails
        run: |
          docker logs nucliadb-server > nucliadb-server.log 2>&1
          docker logs pg > postgres.log

      - name: Upload Docker Logs
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: docker-logs
          path: |
            nucliadb-server.log
            postgres.log
          if-no-files-found: ignore
      - name: Slack notification
        id: slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        if: ${{ failure() && steps.cypress.conclusion == 'failure' }}
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_HOOK_URL }}
          payload: |
            {
              "text": "‼️️Cypress E2E failed on PROD ‼️\nRun #${{ github.run_number }}: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\nCypress report: ${{ steps.report.outputs.artifact-url }}"
            }
