name: run-e2e-prod
run-name: Running Cypress e2e tests on prod
on:
  push:
    branches:
      - e2e-on-prod
  workflow_dispatch:
    branches:
      - e2e-on-prod
  schedule:
    # Run at minute 35 past every 3rd hour on every day-of-week from Sunday through Saturday.
    - cron: '45 */3 * * 0-6'
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Launch NucliaDB in docker
      - run: |
          docker pull nuclia/nucliadb:latest
          docker build -t nucliadb-server .
          docker run -p 8080:8080 \
              -v nucliadb-standalone:/data \
              -e NUA_API_KEY=${{ secrets.NUA_KEY_PROD_EUROPE }} \
              nucliadb-server &
      # Install npm dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn install
        env:
          CYPRESS_BEARER_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_PROD }}
          CYPRESS_NUA_KEY_EUROPE: ${{ secrets.NUA_KEY_PROD_EUROPE }}
          CYPRESS_NUA_KEY_USA: ${{ secrets.NUA_KEY_PROD_USA }}
          CYPRESS_USER_NAME: ${{ secrets.USER_NAME_PROD }}
          CYPRESS_USER_PWD: ${{ secrets.USER_PWD_PROD }}
          CYPRESS_RUNNING_ENV: prod
        # after the test run completes store reports and any screenshots
      - name: Cypress reports
        uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.cypress.conclusion == 'failure' }}
        with:
          name: cypress-reports
          path: cypress/reports
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - name: Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.25.0
        if: ${{ failure() && steps.cypress.conclusion == 'failure' && github.ref_name == 'main' }}
        with:
          payload: |
            {
              "text": "‼️⚠️ Cypress E2E failed on Prod ‼️\nRun #${{ github.run_number }}: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n📜Cypress report: ${{ steps.report.outputs.artifact-url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK