name: run-benchmark-prod
run-name: Running PROD NUCLIA benchmark
on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/run-benchmark-prod.yml'  # Runs only if this file is modified
  workflow_dispatch:  # Allow manual run from any branch
  schedule:
    # Run every day at 04:25
    - cron: '25 4 * * *'
jobs:
  test:
    runs-on: nuclia-base
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r nuclia_e2e/requirements.txt
          pip install -e nuclia_e2e

      - name: Run Benchmark
        env: # Or as an environment variable
          PROD_PERMAMENT_ACCOUNT_OWNER_PAT_TOKEN: ${{ secrets.PROD_PERMAMENT_ACCOUNT_OWNER_PAT_TOKEN }}
          PROD_ROOT_PAT_TOKEN: ${{ secrets.PROD_ROOT_PAT_TOKEN }}
          PROD_GLOBAL_RECAPTCHA: ${{ secrets.PROD_GLOBAL_RECAPTCHA }}
          TEST_EUROPE1_NUCLIA_NUA: ${{ secrets.TEST_EUROPE1_NUCLIA_NUA }}
          TEST_AWS_US_EAST_2_1_NUCLIA_NUA: ${{ secrets.TEST_AWS_US_EAST_2_1_NUCLIA_NUA }}
          TEST_GMAIL_APP_PASSWORD: ${{ secrets.TEST_GMAIL_APP_PASSWORD }}
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
        run: |
          TEST_ENV=prod TEST_ZONES="europe-1" pytest -sxv -r fEs nuclia_e2e/nuclia_e2e/tests/benchmarking --durations=0
