name: run-e2e-dev-extended
run-name: Running Extended Cypress e2e tests on Dev
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    permissions:
      contents: read # actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install
        run: |-
          yarn install --immutable
          node_modules/.bin/cypress install
      - name: Cypress run
        id: cypress
        uses: cypress-io/github-action@f790eee7a50d9505912f50c2095510be7de06aa7 # v6.10.9
        with:
          spec: cypress/e2e/extended/**/*.cy.js
        env:
          CYPRESS_BASE_URL: https://gcp-global-dev-1.nuclia.io
          CYPRESS_BEARER_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN_DEV }}
          CYPRESS_NUA_KEY: ${{ secrets.NUA_KEY_DEV }}
          CYPRESS_USER_NAME: ${{ secrets.USER_NAME_DEV }}
          CYPRESS_USER_PWD: ${{ secrets.USER_PWD_DEV }}
          CYPRESS_RUNNING_ENV: dev
        # after the test run completes store reports and any screenshots
      - name: Cypress reports
        id: report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ failure() && steps.cypress.conclusion == 'failure' }}
        with:
          name: cypress-reports
          path: cypress/reports
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - name: Slack notification
        id: slack
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        if: ${{ failure() && steps.cypress.conclusion == 'failure' && github.ref_name == 'main' }}
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_HOOK_URL }}
          payload: |
            {
              "text": "⚠️ Extended Cypress E2E failed on Dev\nTriggered by ${{ github.triggering_actor }} \nRun #${{ github.run_number }}: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\nCypress report: ${{ steps.report.outputs.artifact-url }}"
            }
