name: run-nua-e2e-prod
run-name: Running e2e PROD NUA tests
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    branches:
      - main
  schedule:
    # run every at every saturdat at 12
    - cron: '25 4 * * 6'
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Launch NucliaDB in docker

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r nua/requirements.txt

      - name: Install dependencies
        env: # Or as an environment variable
          TEST_EUROPE1_STASHIFY_NUA: ${{ secrets.TEST_EUROPE1_STASHIFY_NUA }}
          TEST_EUROPE1_NUCLIA_NUA: ${{ secrets.TEST_EUROPE1_NUCLIA_NUA }}
          TEST_AWS_US_EAST_2_1_NUCLIA_NUA: ${{ secrets.TEST_AWS_US_EAST_2_1_NUCLIA_NUA }}
        run: |
          pytest nua/e2e --durations=0 --junitxml nua.xml   

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'nua.xml'
      - name: Discord notification
        uses: cl8dep/action-discord@0.1
        if: ${{ failure() && github.ref_name == 'main' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_NUA }}
          message: |
            ⚠️ tests failed @NUA
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>
          username: 'NUA E2E'