name: run-nua-e2e-gke-stage-1
run-name: Running e2e GKE-STAGE-1 NUA tests
on:
  workflow_call:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Launch NucliaDB in docker

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r nua/requirements.txt

      - name: Hack host file for gke-stage-1 test
        run: |
          echo "34.149.145.147 europe-1.stashify.cloud." | sudo tee -a /etc/hosts > /dev/null

      - name: Run tests
        env: # Or as an environment variable
          TEST_EUROPE1_STASHIFY_NUA: ${{ secrets.TEST_EUROPE1_STASHIFY_NUA }}
        run: |
          TEST_ENV=stage pytest nua/e2e --durations=0 --junitxml nua.xml   

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'nua.xml'

      - name: Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        if: ${{ failure() && github.ref_name == 'main' }}
        with:
          payload: |
            {
              "text": "⚠️ tests failed on STAGE\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.NUA_E2E_SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK